parameters:
    acdatabundle.db.table_prefix: ac
services:
            acdatabundle.tblprefix_subscriber:
                class: ac\DataBundle\Subscriber\TablePrefixSubscriber
                arguments: [%acdatabundle.db.table_prefix%]
                tags:
                    - { name: doctrine.event_subscriber }

