ac\DataBundle\Entity\Image:
    type: entity
    table: null
    repositoryClass: ac\DataBundle\Entity\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        originalName:
            type: string
            length: 255
        path:
            type: string
            length: 255
    lifecycleCallbacks: {  }
