ac\DataBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: ac\DataBundle\Entity\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        postTitle:
            type: string
            length: 255
        postContent:
            type: text
        creationDate:
            type: datetime
        modificationDate:
            type: datetime
        status:
            type: string
            length: 255
        commentStatus:
            type: boolean
        commentCount:
            type: integer
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: Post
            joinColumn:
                name: categoryId
                referencedColumnName: id
        user:
            targetEntity: User
            inversedBy: Post
            joinColumn:
                name: userId
                referencedColumnName: id
   
    lifecycleCallbacks: {  }
