ac\DataBundle\Entity\Role:
    type: entity
    table: null
    repositoryClass: ac\DataBundle\Entity\RoleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        roleName:
            type: string
            length: 255
    oneToMany:
       users:
           targetEntity: UserRole
           mappedBy: role          
        
#    manyToMany:
#        users:
#          targetEntity: User
#          inversedBy: Role
#          joinByTable:
#            name: UserRole
#            joinByColumns:
#              roleId:
#                referencedColumnName: id
#                nullable: false
#            inverseJoinColumns:
#                userId:
#                referencedColumnName: id
#                nullable: false
    lifecycleCallbacks: {  }
