ac\DataBundle\Entity\Role:
    type: entity
    table: null
    repositoryClass: ac\DataBundle\Entity\RoleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        roleName:
            type: string
            length: 255
    lifecycleCallbacks: {  }
