parameters:
    accmsadminbundle.db.table_prefix: ac
services:
            accmsadminbundle.tblprefix_subscriber:
                class: ac\CmsAdminBundle\Subscriber\TablePrefixSubscriber
                arguments: [%accmsadminbundle.db.table_prefix%]
                tags:
                    - { name: doctrine.event_subscriber }
